# Generated by Django 5.2.5 on 2026-06-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='has_half_bedroom',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathroom_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_available',
            field=models.DateField(),
        ),
    ]
